# Einführung in Python

Dieses Tutorial stützt sich stark auf [dieses Tutorial über Audiosignalverarbeitung](https://github.com/spatialaudio/selected-topics-in-audio-signal-processing-exercises).

Für die Übungen werden wir die sehr beliebte Programmiersprache [Python](https://www.python.org) zusammen mit einigen externen Bibliotheken aus dem [Scientific Python Stack](http://scipy.org) verwenden.
Für den Anfang können Sie auch einen Blick auf diese werfen:

* [Python Einführung](http://nbviewer.ipython.org/github/mgeier/python-audio/blob/master/intro-python.ipynb) (reines Python, kein NumPy)

* [Simple Signal Processing Example](http://nbviewer.ipython.org/github/mgeier/python-audio/blob/master/simple-signals.ipynb) (ziemlich ähnlich zu den Dingen auf dieser Seite)

Beachten Sie, dass Python nicht die einzige Option für die Art von Aufgaben ist, die wir hier angehen werden.
Wenn Sie sich für einige Alternativen interessieren, schauen Sie sich [Julia](http://julialang.org/), [R](http://www.r-project.org/), [Octave](http://octave.org/) oder [Scilab](http://www.scilab.org/) an.
Alle genannten Anwendungen sind Open-Source-Software und es gibt natürlich noch mehr Alternativen (sowohl kostenlose als auch proprietäre).

Die meisten Übungen in diesem Kurs (einschließlich derjenigen, die Sie gerade lesen) werden als [Jupyter (früher bekannt als IPython) notebooks](http://jupyter.org/) präsentiert.
Sie können [online](http://nbviewer.jupyter.org/github/spatialaudio/communication-acoustics-exercises/blob/master/index.ipynb) angesehen werden, aber es ist viel sinnvoller, sie herunterzuladen und sie lokal mit [Jupyter](http://jupyter.org/) zu öffnen und zu erkunden.

Anweisungen zur Installation finden Sie im Abschnitt [Getting Started](index.ipynb#Getting-Started) auf der Hauptseite.

Um eine Vorstellung davon zu bekommen, worum es bei Jupyter geht, werfen Sie einen Blick auf diese [Jupyter-Einführung](http://nbviewer.jupyter.org/github/mgeier/python-audio/blob/master/intro-jupyter.ipynb).

## Was werden wir heute lernen?

* Grundlagen von Python, Jupyter/IPython, NumPy, SciPy, matplotlib und einigen anderen externen Bibliotheken

## Notebook Cells

Das Notebook besteht aus sogenannten "Zellen", die für normalen Text (siehe oben) oder für Python-Code (siehe unten) verwendet werden können.
*Code-Zellen* können per Mausklick (oder mit den Pfeiltasten nach oben/unten und *Enter*) ausgewählt werden, der Code kann bearbeitet und dann durch Drücken von *Shift+Enter* oder durch Anklicken der <button class="fa fa-step-forward fa-play icon-play btn btn-xs btn-default"></button> Schaltfläche im oberen Teil der Seite ausgeführt werden.

Seien Sie nicht schüchtern, probieren Sie es aus:

In [ ]:
50 - 5 * 4 + 12
a = 10

Codezellen können aus mehreren Zeilen bestehen (verwenden Sie *Enter* für Zeilenumbrüche).
Wenn die Codezelle ausgeführt wird, werden alle Zeilen ausgeführt, aber nur der Wert der letzten Zeile wird angezeigt (es sei denn, es gibt keinen Wert anzuzeigen).

Hier ist eine weitere Codezelle, mit der Sie spielen können:

Neue Zellen können durch Drücken der Tasten *a* oder *b* (zum Einfügen *oberhalb* oder *unterhalb* der aktuellen Zelle) oder über das Menü eingefügt werden. Sie sollten auch einen Blick auf "Hilfe" -> "Tastaturkürzel" werfen.

Durch wiederholtes Drücken der Tastenkombination *Umschalttaste+Eingabetaste* können Sie alle Zellen des Notebooks durchlaufen.
Alternativ können Sie auch im Menü "Run" auf "Run All Cells" klicken.

# Basics
Im Folgenden finden Sie ein Python-Programm, das viele der typischerweise benötigten Operationen enthält: Zuweisungen, Arithmetik, logische Operatoren, Ausgabe, Kommentare. Wie Sie sehen, ist Python recht einfach zu lesen. Ich bin sicher, Sie können die Bedeutung jeder Zeile selbst herausfinden.

In [ ]:
x = 34 - 23 # A comment.
y = "Hello" # Another one.
z = 3.45
if z == 3.45 or y == "Hello":
    x = x + 1
    y = y + " World"
print(x)
print(y)

## Einrückung
Python behandelt Blöcke anders als andere Programmiersprachen, die Sie vielleicht kennen, wie Java oder C: Die erste Zeile mit weniger Einrückung steht außerhalb des Blocks, die erste Zeile mit mehr Einrückung beginnt einen verschachtelten Block. Ein Doppelpunkt leitet oft einen neuen Block ein. Im nachstehenden Code wird zum Beispiel die vierte Zeile immer ausgeführt, da sie nicht Teil des Blocks ist:

In [ ]:
if 17<16:
    print("executed conditionally")
    print("also conditionally")
print("always executed, because not part of the block above")

## Referenz-Semantik
Zuweisungen verhalten sich so, wie Sie es vielleicht aus Java kennen: Für atomare Datentypen funktionieren Zuweisungen "by value", für alle anderen Datentypen (z.B. Listen) funktionieren Zuweisungen "by reference": Wenn wir ein Objekt manipulieren, wirkt sich das auf alle Referenzen aus.

In [ ]:
a=17
b=a #assign the *value* of a to b
a=12
print(b) #still 12, because assinment by value

x=[1,2,3] #this is what lists look like
y=x #assign reference to the list to y
x.append(4) #manipulate the list by adding a value
print(y) #y also changed, because of assingment by reference

# Listen
Listen werden in eckigen Klammern geschrieben, wie Sie oben gesehen haben. Listen können Werte gemischten Typs enthalten. Listenindizes beginnen mit 0, wie Sie hier sehen können:

In [ ]:
li = [17,"Hello",4.1,"Bar",5,6]
li[3]

'Bar'

Sie können auch negative Indizes verwenden, d. h. wir beginnen die Zählung von rechts:

In [ ]:
li[-3]

'Bar'

Sie können auch Teilmengen von Listen auswählen ("slicing"), etwa so:

In [ ]:
li[2:5]

Beachten Sie, dass das Slicing eine Kopie der Teilliste zurückgibt.

## Einige weitere Listenoperatoren
Hier sind einige weitere Operatoren, die Sie vielleicht nützlich finden.

In [ ]:
# Boolean test whether a value is in a list: the in operator
t = [1,2,3,4]
print(2 in t)

# Concatenate lists: the + operator
a = [1,2,3,4]
b = [5,6,7]
c = a + b
print(c)

# Repeat a list n times: the * operator
a=[1,2,3]
3*a

# Append lists
a=[1,2,3]
a.append(4)

# Index of first occurence
a.index(2)

# Number of occurences
a = [1,2,3,2,1,2]
a.count(2)

# Remove first occurence
a.remove(2)

# Revese the list
a.reverse()

# Sort the list
a.sort()

True
[1, 2, 3, 4, 5, 6, 7]


*Aufgabe*: Probieren Sie aus was passiert, wenn Sie eine Liste von Strings mit den unten verwendeten Methoden sortieren! Was könnte der Grund für das gezeigte Verhalten sein?

In [ ]:
string_list = ['c', 'd', 'a', 'y', 'x']
# Sorting with sorted()-method
print('Original string_list: ', string_list)
print('Value which is returned by sorted()-method: ', sorted(string_list))

# Sorting with sort()-method
print('Original string_list: ', str(string_list))
print('Value which is returned by sort()-method: ', string_list.sort())


Original string_list:  ['c', 'd', 'a', 'y', 'x']
Value which is returned by sorted()-method:  ['a', 'c', 'd', 'x', 'y']
Original string_list:  ['c', 'd', 'a', 'y', 'x']
Value which is returned by sort()-method:  None


In [ ]:
print(string_list.sort())

None


## Dictionaries: Ein Mapping-Typ
Dictionaries sind in anderen Sprachen als Maps bekannt: Sie speichern eine Zuordnung zwischen einer Menge von Schlüsseln und einer Menge von Werten. Im Folgenden finden Sie ein Beispiel für die Verwendung von Dictionaries:

In [ ]:
# Create a new dictionary
d = {'user':'bozo',
     'pswd':1234}

# Access the values via a key
print('Value for key \'user\': ', d['user'])

# Add key-value pairs
d['id'] = 17

# List of keys
print('List of keys: ', d.keys())

# List of values
print('List of values: ', d.values())

Value for key 'user':  bozo
List of keys:  dict_keys(['user', 'pswd', 'id'])
List of values:  dict_values(['bozo', 1234, 17])


# Funktionen
Funktionen in Python funktionieren so, wie Sie es erwarten würden: Argumente an Funktionen werden durch Zuweisung übergeben, das heißt, übergebene Argumente werden lokalen Namen zugewiesen. Zuweisungen an Argumente können sich nicht auf den Aufrufer auswirken, aber veränderbare Argumente können sich ändern. Hier ist ein Beispiel für die Definition und den Aufruf einer Funktion:


In [ ]:
def myfun(x: int, y: float):
    print("The function is executed.")
    y[0]=8 # This changes the list that y points to
    return(y[1]+x)

mylist = [1,2,3]
result=myfun(17,mylist)
print("Function returned: ",result)
print("List is now: ",mylist)

Beachten Sie, das `x: int` eine sogenannter *Type-Hint* ist. Das bedeutet, dass das `int` nach dem `:` vom Python-Interpreter nicht beachtet wird. Diese Art von Anotation soll also dem Entwickler nur ein Hinweis darauf geben, welchen Datentypen für welchen Parameter er erwarten kann, erzwingt aber keine Typsicherheit in Python!

## Optionale Argumente
Wir können Standardwerte für Argumente definieren, die nicht übergeben werden müssen:

In [ ]:
def func(a, b, c=10, d=100):
    print(a, b, c, d)
type(func(b=1,a=2))
myfun(1,2)

Einige weitere Fakten über Funktionen:
* Alle Funktionen in Python haben einen Rückgabewert, Funktionen ohne Rückgabewert haben den speziellen Rückgabewert `None` (wie z. B. die sort()-Funktion)
* Es gibt keine Funktionsüberladung in Python.
* Funktionen können wie jeder andere Datentyp verwendet werden: Sie können Argumente für Funktionen sein, Rückgabewerte von Funktionen, Variablen zugewiesen, usw. Das bedeutet, dass Python eine funktionale Programmiersprache ist, und wir können viele Dinge tun, die Sie aus Haskell kennen und lieben, wie Funktionen höherer Ordnung oder auch Lambda-Ausdrücke!

# Kontrollstrukturen
Wir haben oben bereits If-Anweisungen gesehen. For- und While-Schleifen funktionieren auch genau so, wie Sie es erwarten würden, hier sind nur einige Beispiele:

In [ ]:
x = 3
while x < 10:
    if x > 7:
        x += 2
        continue
    x = x + 1
    print("Still in the loop.")
    if x == 8:
        break
print("Outside of the loop.")

In [ ]:
for x in range(10):
    if x > 7:
        x += 2
        continue
    x = x + 1
    print("Still in the loop, x= " , x)
    if x == 8:
        break
print("Outside of the loop, x= " , x)

Still in the loop, x=  1
Still in the loop, x=  2
Still in the loop, x=  3
Still in the loop, x=  4
Still in the loop, x=  5
Still in the loop, x=  6
Still in the loop, x=  7
Still in the loop, x=  8
Outside of the loop, x=  8


*Aufgabe*: Implementieren Sie eine Funktion, die prüft, ob eine gegebene Zahl eine Primzahl ist.

In [1]:
def isPrime(n: int) -> int:
    for i in range(2,n):
      if n%i==0:
        return 0
    return 1


isPrime(17)

1

# List Comprehensions
Es gibt eine spezielle Syntax für List Comprehensions (die Sie vielleicht aus Haskell kennen).

In [ ]:
evens1 = []
for x in range(3,100):
    if x%3 == 0:
        evens1.append(x)
print(evens1)

# List of all multiples of 3 that are <100:
evens2 = [x for x in range(3,100) if x%3==0]
print(evens2)

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]
[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]


Aufgabe: Erstellen Sie mit Hilfe eines List Comprehension eine Liste aller Primzahlen < 1000.

In [2]:
primes = [x for x in range(1,101) if isPrime(x)]
print(primes)

[1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


# Numpy
Numpy ist ein sehr beliebtes Python-Paket, das die Arbeit mit numerischen Arrays erleichtert. Es ist die Grundlage für vieles, was Sie in diesem Kurs sehen werden.

## Importieren von Modulen/Paketen

Um mit numerischen Arrays arbeiten zu können, importieren wir das Paket [NumPy](http://www.numpy.org).

In [3]:
import numpy as np

Jetzt können wir alle NumPy-Funktionen verwenden (durch Voranstellen von "`np.`").

In [4]:
np.zeros(10000)

array([0., 0., 0., ..., 0., 0., 0.])

## Tabulatorvervollständigung

*Übung:* Tippen Sie "`np.ze`" (ohne Anführungszeichen) und drücken Sie dann die *Tab*-Taste ...

## Array, Vektor, Matrix

Arrays können beliebig viele Dimensionen haben, aber lassen Sie uns für den Moment nur eindimensionale Arrays verwenden.
Arrays können mit [numpy.array()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html) erstellt werden:

In [5]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Beachten Sie, dass das Ergebnis nicht angezeigt wird, wenn Sie einer Variablen einen Wert zuweisen (da die Zuweisung eine *Anweisung* und kein *Ausdruck* ist).
Um die Daten anzuzeigen, schreiben Sie den Variablennamen separat in die letzte (oder einzige) Zeile einer Codezelle.

In [6]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Übrigens gibt es einen einfacheren Weg, dieses spezielle Array zu erhalten (mit [numpy.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)):

In [11]:
b = np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Hilfe erhalten

Wenn Sie Einzelheiten über die Verwendung von `np.arange()` und alle unterstützten Argumente wissen wollen, werfen Sie einen Blick in den Hilfetext.
Hängen Sie einfach ein Fragezeichen an den Funktionsnamen (ohne Klammern!):

In [ ]:
np.arange?

Im unteren Teil des Browserfensters sollte sich ein Hilfefenster öffnen.
Dieses Fenster kann durch Drücken der Taste *q* (wie "quit") geschlossen werden.

Holen wir uns mehr Hilfe:

In [ ]:
np.zeros?

Sie können auch Hilfe für das gesamte NumPy-Paket erhalten:

In [ ]:
np?

Sie können für jedes Objekt Hilfe erhalten, indem Sie ein Fragezeichen an den Namen des Objekts anhängen (oder voranstellen).
Schauen wir uns an, was das Hilfesystem uns über unsere Variable `a` sagen kann:

In [ ]:
a?

Das Hilfesystem kann bei der Lösung der folgenden Aufgaben sehr nützlich sein ...

## `np.arange()`

Wir werden oft Sequenzen von gleichmäßig verteilten Zahlen brauchen, also lasst uns welche erstellen.

*Übung:* Erzeugen Sie eine Zahlenfolge mit `np.arange()`, beginnend mit 0 und bis (aber nicht einschließlich) 6 mit einer Schrittweite von 1.

In [ ]:
'Implement me!'

*Übung:* Erzeugen Sie eine Zahlenfolge mit `np.arange()`, beginnend mit 0 und bis (aber nicht einschließlich) 0,6 mit einer Schrittweite von 0,1.

In [16]:
a=np.arange(0,0.6,0.1)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5])

*Übung:* Erzeugen Sie eine Zahlenfolge mit `np.arange()`, beginnend mit 0,5 bis (aber nicht einschließlich) 1,1 mit einer Schrittweite von 0,1.

In [18]:
a=np.arange(0.5,1.1,0.1)
a

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1])

Die vorherige Übung ist etwas knifflig.
Wenn Sie es richtig gemacht haben, schauen Sie unter [arange considered harmful](http://nbviewer.ipython.org/github/mgeier/python-audio/blob/master/misc/arange.ipynb) nach, was Sie falsch gemacht haben *könnten*.
Wenn Sie ein unerwartetes Ergebnis erhalten haben, schauen Sie unter [arange considered harmful](http://nbviewer.ipython.org/github/mgeier/python-audio/blob/master/misc/arange.ipynb) nach einer Erklärung.

*Übung:* Können Sie das Problem beheben?

In [21]:
a=np.arange(0.5,1.09,0.1)
a

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Was lernen wir aus all dem?
$\Rightarrow$
`np.arange()` ist großartig, aber verwenden Sie es nur mit ganzzahligen Schrittweiten!

## `np.linspace()`

Eine andere, etwas andere Methode, um eine Folge von Zahlen mit gleichmäßigen Abständen zu erzeugen, ist [numpy.linspace()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html).
Werfen Sie einen Blick in die Dokumentation.

In [22]:
np.linspace?

*Übung:* Erzeugen Sie eine Zahlenfolge mit `np.linspace()`, beginnend mit 0 und bis (einschließlich) 6 mit einer Schrittweite von 1.

In [32]:
a=np.linspace(0, 6, 7)
a

array([0., 1., 2., 3., 4., 5., 6.])

Beachten Sie, dass das resultierende Array einen *Gleitkomma*-Datentyp hat, auch wenn alle Eingaben (und die Schrittweite) Ganzzahlen sind.
Dies ist bei `np.arange()` nicht der Fall.

*Übung:* Erzeugen Sie mit `np.linspace()` eine Folge von Zahlen, beginnend mit 0 und bis (aber nicht einschließlich) 6 mit einer Schrittweite von 1.

In [48]:
a=np.linspace(0, 6, 6, endpoint=False)
a

array([0., 1., 2., 3., 4., 5.])

*Übung:* Erzeugen Sie eine Zahlenfolge mit `np.linspace()`, beginnend mit 0 und bis (aber nicht einschließlich) 0,6 mit einer Schrittweite von 0,1.

In [49]:
a=np.linspace(0, 0.6, 6, endpoint=False)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5])

*Übung:* Erzeugen Sie eine Zahlenfolge mit `np.linspace()`, beginnend mit 0,5 und bis zu (aber nicht einschließlich) 1,1 mit einer Schrittweite von 0,1.

In [50]:
a=np.linspace(0.5, 1.1, 6, endpoint=False)
a

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Beachten Sie, dass `np.linspace()` nicht das oben erwähnte Problem hat, das wir mit `np.arange()` hatten.

## Erstellen einer Sinuswelle

Erstellen wir nun ein interessanteres Array, das ein digitales Sinussignal darstellt. Das Signal folgt der Gleichung $y(t) = A\sin(\omega t)$ mit $\omega = 2\pi f$ und $f$ ist die Frequenz des Sinus.
Die maximale Signalamplitude ist durch $A$ gegeben.
Die Variable $t$ steht natürlich für die Zeit.
Wir wollen ein digitales Signal mit gleichmäßig verteilten Werten für $t$ erzeugen.

Wir können die Funktion [numpy.sin()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.sin.html) verwenden, um einen Sinuston zu erzeugen. Schauen wir uns zunächst den Hilfetext an.

In [51]:
np.sin?

Da wir nun wissen, welche Funktion wir aufrufen müssen, brauchen wir eine geeignete Eingabe.
Und hier kommen unsere Sequenzen von gleichmäßig verteilten Werten von oben ins Spiel.

Das Schöne an NumPy-Funktionen wie `np.sin()` ist, dass sie auf ganze Arrays auf einmal wirken können, so dass es nicht notwendig ist, die Funktion für jeden einzelnen Wert separat aufzurufen.
Daher können wir den gesamten Wertebereich für unsere Zeitvariable $t$ in einem Array speichern.

Gemäß der Gleichung muss jeder Wert von $t$ mit (der Konstante) $\omega$ multipliziert werden.
Das ist eine weitere nette Sache an NumPy: wir müssen nicht jeden Wert des Arrays $t$ einzeln mit $\omega$ multiplizieren, wir können das ganze Array auf einmal mit einem Skalar multiplizieren, und NumPy übernimmt die elementweise Multiplikation für uns.
Dies wird ["broadcasting"](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) genannt, falls Sie über dieses Wort in der Dokumentation stolpern.
Das Array, das von `np.sin()` zurückgegeben wird, kann (wiederum mittels Broadcasting) mit dem konstanten Skalar $A$ multipliziert werden, um das Endergebnis zu erhalten.

Das einzige, was noch fehlt, ist $\pi$, aber das ist einfach:

In [52]:
np.pi

3.141592653589793

Nun wollen wir eine Sinuswelle mit einer Frequenz von 2 Hz, einer Dauer von 1 Sekunde und einer Amplitude von 0,3 erzeugen.
Wir verwenden eine Abtastrate von 44,1 kHz.

In [ ]:
dur = 1  # duration in seconds
amp = 0.3  # maximum amplitude
freq = 2  # frequency of the sine tone in Hertz
fs = 44100  # sampling frequency in Hertz

t = np.arange(np.ceil(dur * fs)) / fs
y = amp * np.sin(2 * np.pi * freq * t)

## Plotten

Python und NumPy können nicht selbst plotten, sie benötigen die Hilfe von [matplotlib](http://matplotlib.org/).

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

Jetzt können wir die Daten aus unserem Array aufzeichnen:

In [ ]:
plt.plot(y)

Wie immer, für weitere Informationen:

In [ ]:
%matplotlib?

## Verändern des Plots

Schauen wir uns noch einmal unseren Plot an.

In [ ]:
plt.plot(y);

Da wir nur ein einziges Array an die Funktion `plot()` übergeben haben, zeigt die x-Achse den Sample-Index von 0 bis zur Länge des Signals in Samples (minus eins).
Es könnte sinnvoller sein, die Zeit in Sekunden anzugeben.

Aber lassen Sie uns zuerst die vorherige Darstellung schließen.

In [ ]:
plt.close()

Wenn wir zwei Arrays an die Funktion `plot()` übergeben, definiert das erste die Zuordnung von Stichprobenindizes zu den tatsächlichen Werten, die auf der x-Achse angezeigt werden, das zweite gibt die entsprechenden y-Werte an.

In [ ]:
plt.plot(t, y);

Gut, jetzt zeigt die x-Achse die Zeit in Sekunden an.
Lassen Sie uns Achsenbeschriftungen erstellen, damit jeder Bescheid weiß.

In [ ]:
plt.plot(t, y)
plt.xlabel("Time / Seconds")
plt.ylabel("Amplitude")
plt.title("Sine Tone with {} Hz".format(freq));

Weitere Informationen finden Sie unter [Getting Started With `matplotlib`](http://nbviewer.ipython.org/github/mgeier/python-audio/blob/master/plotting/matplotlib.ipynb).

## Zweidimensionale Arrays

Zweidimensionale Arrays sehen ein wenig aus wie Listen von Listen, aber intern werden sie immer noch in einem zusammenhängenden Speicherbereich gespeichert.

Es gibt mehrere Funktionen zur Erstellung von Arrays, mit denen die Anzahl der Zeilen und Spalten angegeben werden kann, z. B. [numpy.zeros()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html) und [numpy.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html).

In [ ]:
np.zeros((4, 2))

In [ ]:
np.ones((4, 2))

Arrays können auch aus Listen von Listen (auch bekannt als *verschachtelte* Listen) mit [numpy.array()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html) erstellt werden:

In [ ]:
np.array([[.1, .2], [.3, .4], [.5, .6], [.7, .8]])

Beachten Sie, dass die inneren Listen die einzelnen Zeilen des Arrays liefern.

Zweidimensionale Arrays können auch durch spaltenweises Verketten einer Liste von eindimensionalen Arrays (oder Listen) mit [numpy.column_stack()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.column_stack.html) erstellt werden:

In [ ]:
a = np.column_stack([[.1, .2, .3, .4], [.5, .6, .7, .8]])
a

Wenn Sie Zeilen und Spalten umdrehen wollen, können Sie das Array transponieren:

In [ ]:
a.T


Das transponierte Array ist *nicht* eine Kopie des ursprünglichen Arrays, es ist vielmehr eine andere *Sicht* auf denselben Speicher.
Das heißt, wenn Sie ein Element des transponierten Arrays ändern, wird diese Änderung auch im ursprünglichen Array sichtbar!

In [ ]:
b[1, 2] = 0
a

## Array-Eigenschaften

Lassen Sie uns ein zweidimensionales Array erstellen:

In [ ]:
x = np.random.normal(scale=0.2, size=(int(1.5 * fs), 2))
x

*Übung:* Probieren Sie diese verschiedenen Möglichkeiten aus, um die Größe des Feldes zu erhalten:

In [ ]:
len(a)

In [ ]:
a.shape

In [ ]:
a.size

In [ ]:
a.nbytes

*Übung:* Es gibt noch viel mehr Informationen über das Array, probiere die folgenden Befehle aus und finde heraus, was sie bedeuten.

In [ ]:
x.ndim

In [ ]:
x.dtype

In [ ]:
x.itemsize

In [ ]:
x.strides

In [ ]:
x.flags

*Übung:*
Sie können auch einige statistische Werte über die Daten im Array erhalten.
Prüfen Sie, ob sie mit dem gegebenen normalverteilten Rauschsignal übereinstimmen.

In [ ]:
x.max()

In [ ]:
x.min()

In [ ]:
x.ptp()

In [ ]:
x.mean()

In [ ]:
x.std()

In [ ]:
x.var()

Die meisten dieser *Methoden* existieren auch als *Funktionen*, z.B.

In [ ]:
np.max(x)

Sowohl die Funktionen als auch die Methoden haben ein optionales Argument *Achse*.

*Übung:* Versuchen Sie `axis=0` mit allen oben genannten Funktionen/Methoden.

In [ ]:
x.std(axis=0)

In [ ]:
np.mean(x, axis=0)

*Übung:* Was ist der Unterschied zwischen `axis=0` und `axis=1`?
Was bedeutet `axis=-1`?

## Broadcasting

Wir haben bereits gesehen, dass wenn ein Skalar mit einem Array multipliziert wird, diese Multiplikation elementweise auf dem Array durchgeführt wird.
Die NumPy-Leute nennen dies [broadcasting](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

Das Tolle daran ist, dass es nicht auf Operationen zwischen einem Skalar und einem Array beschränkt ist, sondern auch zwischen Arrays unterschiedlicher Anzahl von Dimensionen.

Nehmen wir zum Beispiel ein eindimensionales Array mit zwei Werten und multiplizieren es mit unserem zweidimensionalen Array `x` von vorhin:

In [ ]:
np.array([0.5, 100]) * x

Obwohl diese beiden Arrays eindeutig eine unterschiedliche Form und eine unterschiedliche Anzahl von Dimensionen haben, hat die Multiplikation funktioniert.
In diesem Fall wurde jedes Element der ersten Spalte von "x" mit dem ersten Wert der anderen Matrix multipliziert, und dasselbe gilt für die zweite Spalte und den zweiten Wert der Matrix.

In diesem Beispiel hat das Ergebnis die gleiche Form wie einer der Operanden, und der andere Operand wurde entlang seiner einzigen (oder eher fehlenden) Dimension "gestreckt".

Aber das muss nicht so sein.
Erstellen wir ein zweidimensionales Array, das nur aus einer Spalte besteht:

In [ ]:
y = np.random.normal(scale=0.2, size=(int(1.5 * fs), 1))
y

In [ ]:
y.shape

Wenn wir ein eindimensionales Array mit diesem zweidimensionalen Spaltenarray multiplizieren, hat keine der Dimensionen die gleiche Größe.
Dennoch können wir sie multiplizieren und beide Felder werden "gestreckt" (entlang ihrer singulären/fehlenden Dimension), was zu einem Ergebnis führt, das eine größere Form hat als einer der Operanden:

In [ ]:
np.array([0.5, 100]) * y

Die linke Spalte des Ergebnisses ist "y" multipliziert mit dem ersten Element der eindimensionalen Matrix, die rechte Spalte ist das gleiche "y" multipliziert mit dem zweiten Element.

<p xmlns:dct="http://purl.org/dc/terms/">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    <img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />
  </a>
  <br />
  To the extent possible under law,
  <span rel="dct:publisher" resource="[_:publisher]">the person who associated CC0</span>
  with this work has waived all copyright and related or neighboring
  rights to this work.
</p>